FROM microsoft/dotnet:2.2.0-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2.100-sdk AS build
WORKDIR /src
COPY API/API.csproj API/
RUN dotnet restore API/API.csproj
COPY . .
WORKDIR /src
RUN dotnet build API/API.csproj -c Release -o /app
FROM build AS publish
RUN dotnet publish API/API.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .

RUN apt-get update 

RUN apt-get -y install potrace
RUN apt-get -y install imagemagick
ENTRYPOINT ["dotnet", "API.dll"]
